### ISSUE TITLE
Uli makes comment text appear reversed on Google Docs

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/Uli#314] opened 2023-07-27 11:55 UTC
**Describe the bug**
Uli makes comments on Google Docs reversed! (experienced on firefox)

**To Reproduce**
1. Ensure you have Uli installed. You don't need to click "Activate Plugin" 
2. Go to Google Docs and create a new document
3. Type a few words
4. Select a word(s)
5. Add a comment
6. Type something in the comments
7. You will notice that whatever you type appears in reverse order. So if you type "Uli", you will see "ilU"

**Expected behavior**
You see what you type in the comment text box

**Screenshots**
![Screenshot 2023-07-27 at 17-24-02 Untitled document - Google Docs](https://github.com/tattle-made/Uli/assets/1415361/81cd69b6-5e5e-41d7-9f1f-75e6ab5c3637)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser firefox
 - Version 115.0.2

**Additional context**
Was reported by a User who spent a day debugging this. Searched for anti virus solutions and eventually Uninstalled Uli to realize Uli was the culprit!

**Comment by dennyabrain** [comment] 2023-07-27 12:01
I just noticed this on whatsapp web also. I think Uli is messing with textboxes. Maybe we need to exclude processing of text boxes.

**Comment by aatmanvaidya** [comment] 2023-08-03 03:58
This is also happening in Gmail and Grammarly (website).

Desktop:
-  OS - Windows
- Browser - Brave
- Version - 1.56.14

**Comment by dennyabrain** [comment] 2023-08-04 02:51
@aatmanvaidya Yes, i think its happening on all text fields.

**Comment by aatmanvaidya** [comment] 2023-08-17 04:48
I have a fix for it!
- The problem is occurring in the `bft` function inside the `transform-general` file in the `browser-extension/plugin` folder.
- the `bft` function is a traversing through DOM nodes to find leaf nodes that are text nodes and applying the `slurReplace()` function on them. 
- Right now, the `slurReplace()` is being applied to all the text on a web page. And the replacement is being done on every text on the webpage too.
### Fixing it
- One simple way is to ignore all the input text boxes altogether. 
- But if we don't want that, we can do this. 
- To not replace every text, to just replace the text that doesn't match the original text (meaning slur replacement is done). 
```
function bft(node) {
    if (node.nodeType === Node.TEXT_NODE) {
        const originalText = node.textContent;
        const replacementText = replaceSlur(originalText);
        if (replacementText !== originalText) {
            node.textContent = replacementText;
        }
    } else if (node.nodeName !== "STYLE" && node.nodeName !== "SCRIPT" && node.nodeName !== "NOSCRIPT") {
        node.childNodes.forEach(bft);
    }
}
```
- Here we use the nodeType TEXT_NODE which is a cleaner way to access all the text nodes in a webpage. 
- https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType
- https://stackoverflow.com/questions/6520192/how-to-get-the-text-node-of-an-element
- But this still doesn't fix the problem because the same problem would occur with words which are blurred by Uli. (detected slurs). 
- because what will happen the cursors will again come forward if a user types a slur word. 
- for instance the user wants to type "crazy stupid", but the user will actually type "stupid crazy" because of this cursor issue. 
- It can be fixed by accessing the cursor and moving it forward. 
```
// Function to get the cursor position within a node
function getCaretCharacterOffsetWithin(element) {
    let caretOffset = 0;
    const sel = window.getSelection();
    if (sel.rangeCount > 0) {
        const range = sel.getRangeAt(0);
        const preCaretRange = range.cloneRange();
        preCaretRange.selectNodeContents(element);
        preCaretRange.setEnd(range.endContainer, range.endOffset);
        caretOffset = preCaretRange.toString().length;
    }
    return caretOffset;
}

// Function to set the cursor position within a node
function setCaretPosition(element, offset) {
    const range = document.createRange();
    const sel = window.getSelection();
    range.setStart(element, offset);
    range.collapse(true);
    sel.removeAllRanges();
    sel.addRange(range);
}

function bft(node) {
    if (node.nodeType === Node.TEXT_NODE) {
        const originalText = node.textContent;
        const originalCursorPosition = getCaretCharacterOffsetWithin(node); // Get cursor position
        const replacementText = replaceSlur(originalText);

        if (replacementText !== originalText) {
            node.textContent = replacementText;
            setCaretPosition(node, originalCursorPosition); // Set cursor position
        }
    } else if (node.nodeName !== "STYLE" && node.nodeName !== "SCRIPT" && node.nodeName !== "NOSCRIPT") {
        node.childNodes.forEach(bft);
    }
}
```
- https://stackoverflow.com/questions/32028479/how-to-move-cursor-to-next-previous-word-in-textarea
- https://stackoverflow.com/questions/41716112/how-to-move-cursor-backwards

**Closed** 2023-08-17 12:08 UTC
Labels: bug, level:ticket
